"""Telegram persona package."""

from .api import TELEGRAM_API_ROOT, TELEGRAM_MAX_MESSAGE_CHARS, TelegramApi, TelegramApiError, is_telegram_polling_conflict
from .async_runner import AsyncBotRunner
from .orchestrator import NikolaBot, build_nikola_bot
from .config import TelegramConfig
from .runner import BotRunner
from .constants import (
    OFFSET_KEY,
    TELEGRAM_CHAT_THREAD_PREFIX,
    TELEGRAM_GLOBAL_MEMORY_TAG,
    TELEGRAM_PERSONA_SELF_MEMORY_TAG,
)
from .identity import (
    DECEPTIVE_IDENTITY_REPLY_RE,
    IDENTITY_QUESTION_RE,
    IMAGE_BLIND_REPLY_RE,
    honest_identity_reply,
    is_deceptive_identity_reply,
    is_identity_question,
    is_image_blind_reply,
)
from .json_io import (
    DECISION_JSON_SCHEMA,
    Decision,
    INITIATIVE_JSON_SCHEMA,
    ImageAttachment,
    InitiativeDecision,
    StickerAttachment,
    decision_from_payload,
    decision_reply_texts,
    extract_json_object,
    image_to_payload,
    initiative_from_payload,
    normalize_goal_actions,
    normalize_reminder_requests,
    normalize_reply_messages,
    normalize_reply_to,
    normalize_sticker_choices,
    normalize_tool_request,
    sticker_to_payload,
)
from .stickers import (
    SERIOUS_STICKER_RE,
    STICKER_ALIASES,
    STICKER_PACKS,
    auto_sticker_choice,
    looks_serious_for_sticker,
    normalize_sticker_pack,
)
from .text import (
    ASSISTANTY_SENTENCE_RE,
    GENERIC_CHECKIN_RE,
    GENERIC_STICKER_FILLER_RE,
    display_sender,
    parse_command,
    split_telegram_message,
    strip_assistanty_phrases,
    strip_speaker_prefixes,
)
from .vision import (
    VISION_BOILERPLATE_PATTERNS,
    VISION_PROMPT_LEAK_RE,
    clean_vision_description,
)
from .voice import VoiceAttachment, VoiceSynthesisConfig, VoiceTranscriptionConfig, VoiceTranscriptionResult


__all__ = [
    "ASSISTANTY_SENTENCE_RE",
    "AsyncBotRunner",
    "BotRunner",
    "DECEPTIVE_IDENTITY_REPLY_RE",
    "DECISION_JSON_SCHEMA",
    "Decision",
    "GENERIC_CHECKIN_RE",
    "GENERIC_STICKER_FILLER_RE",
    "IDENTITY_QUESTION_RE",
    "IMAGE_BLIND_REPLY_RE",
    "INITIATIVE_JSON_SCHEMA",
    "ImageAttachment",
    "InitiativeDecision",
    "NikolaBot",
    "OFFSET_KEY",
    "SERIOUS_STICKER_RE",
    "STICKER_ALIASES",
    "STICKER_PACKS",
    "StickerAttachment",
    "TELEGRAM_API_ROOT",
    "TELEGRAM_CHAT_THREAD_PREFIX",
    "TELEGRAM_GLOBAL_MEMORY_TAG",
    "TELEGRAM_MAX_MESSAGE_CHARS",
    "TELEGRAM_PERSONA_SELF_MEMORY_TAG",
    "TelegramApi",
    "TelegramApiError",
    "TelegramConfig",
    "VISION_BOILERPLATE_PATTERNS",
    "VISION_PROMPT_LEAK_RE",
    "VoiceAttachment",
    "VoiceSynthesisConfig",
    "VoiceTranscriptionConfig",
    "VoiceTranscriptionResult",
    "auto_sticker_choice",
    "build_nikola_bot",
    "clean_vision_description",
    "decision_from_payload",
    "decision_reply_texts",
    "display_sender",
    "extract_json_object",
    "honest_identity_reply",
    "image_to_payload",
    "initiative_from_payload",
    "is_deceptive_identity_reply",
    "is_identity_question",
    "is_image_blind_reply",
    "is_telegram_polling_conflict",
    "looks_serious_for_sticker",
    "normalize_goal_actions",
    "normalize_reminder_requests",
    "normalize_reply_messages",
    "normalize_reply_to",
    "normalize_sticker_choices",
    "normalize_sticker_pack",
    "normalize_tool_request",
    "parse_command",
    "split_telegram_message",
    "sticker_to_payload",
    "strip_assistanty_phrases",
    "strip_speaker_prefixes",
]
