"""Backwards-compatible facade for the Telegram package.

The Telegram bot was refactored into the :mod:`protoagi.telegram` package.
This module re-exports the same public symbols so existing imports such as
``from protoagi.telegram_bot import NikolaBot`` keep working without
changes.
"""

from __future__ import annotations

from .telegram import (  # noqa: F401
    ASSISTANTY_SENTENCE_RE,
    BotRunner,
    DECEPTIVE_IDENTITY_REPLY_RE,
    DECISION_JSON_SCHEMA,
    Decision,
    GENERIC_CHECKIN_RE,
    GENERIC_STICKER_FILLER_RE,
    IDENTITY_QUESTION_RE,
    IMAGE_BLIND_REPLY_RE,
    INITIATIVE_JSON_SCHEMA,
    ImageAttachment,
    InitiativeDecision,
    NikolaBot,
    OFFSET_KEY,
    SERIOUS_STICKER_RE,
    STICKER_ALIASES,
    STICKER_PACKS,
    StickerAttachment,
    TELEGRAM_API_ROOT,
    TELEGRAM_CHAT_THREAD_PREFIX,
    TELEGRAM_GLOBAL_MEMORY_TAG,
    TELEGRAM_MAX_MESSAGE_CHARS,
    TELEGRAM_PERSONA_SELF_MEMORY_TAG,
    TelegramApi,
    TelegramApiError,
    TelegramConfig,
    VISION_BOILERPLATE_PATTERNS,
    VISION_PROMPT_LEAK_RE,
    auto_sticker_choice,
    build_nikola_bot,
    clean_vision_description,
    decision_from_payload,
    decision_reply_texts,
    display_sender,
    extract_json_object,
    honest_identity_reply,
    image_to_payload,
    initiative_from_payload,
    is_deceptive_identity_reply,
    is_identity_question,
    is_image_blind_reply,
    is_telegram_polling_conflict,
    looks_serious_for_sticker,
    normalize_reminder_requests,
    normalize_reply_messages,
    normalize_reply_to,
    normalize_sticker_choices,
    normalize_sticker_pack,
    parse_command,
    split_telegram_message,
    sticker_to_payload,
    strip_assistanty_phrases,
    strip_speaker_prefixes,
)


__all__ = [
    "ASSISTANTY_SENTENCE_RE",
    "BotRunner",
    "DECEPTIVE_IDENTITY_REPLY_RE",
    "DECISION_JSON_SCHEMA",
    "Decision",
    "GENERIC_CHECKIN_RE",
    "GENERIC_STICKER_FILLER_RE",
    "IDENTITY_QUESTION_RE",
    "IMAGE_BLIND_REPLY_RE",
    "INITIATIVE_JSON_SCHEMA",
    "ImageAttachment",
    "InitiativeDecision",
    "NikolaBot",
    "OFFSET_KEY",
    "SERIOUS_STICKER_RE",
    "STICKER_ALIASES",
    "STICKER_PACKS",
    "StickerAttachment",
    "TELEGRAM_API_ROOT",
    "TELEGRAM_CHAT_THREAD_PREFIX",
    "TELEGRAM_GLOBAL_MEMORY_TAG",
    "TELEGRAM_MAX_MESSAGE_CHARS",
    "TELEGRAM_PERSONA_SELF_MEMORY_TAG",
    "TelegramApi",
    "TelegramApiError",
    "TelegramConfig",
    "VISION_BOILERPLATE_PATTERNS",
    "VISION_PROMPT_LEAK_RE",
    "auto_sticker_choice",
    "build_nikola_bot",
    "clean_vision_description",
    "decision_from_payload",
    "decision_reply_texts",
    "display_sender",
    "extract_json_object",
    "honest_identity_reply",
    "image_to_payload",
    "initiative_from_payload",
    "is_deceptive_identity_reply",
    "is_identity_question",
    "is_image_blind_reply",
    "is_telegram_polling_conflict",
    "looks_serious_for_sticker",
    "normalize_reminder_requests",
    "normalize_reply_messages",
    "normalize_reply_to",
    "normalize_sticker_choices",
    "normalize_sticker_pack",
    "parse_command",
    "split_telegram_message",
    "sticker_to_payload",
    "strip_assistanty_phrases",
    "strip_speaker_prefixes",
]
